version: 1.0
ckg_directory: "ckg"
data_directory: "data"
archive_directory: "data/archive"
databases_directory: "data/databases"
experiments_directory: "data/experiments"
ontologies_directory: "data/ontologies"
users_directory: "data/users"
stats_directory: "data/stats"
downloads_directory: "data/downloads"
reports_directory: "data/reports"
tmp_directory: "data/tmp"
imports_directory: "data/imports"
imports_databases_directory: "data/imports/databases"
imports_experiments_directory: "data/imports/experiments"
imports_ontologies_directory: "data/imports/ontologies"
imports_users_directory: "data/imports/users"
imports_curated_directory: "data/imports/curated"
log_directory: "log"
report_manager_log: "ckg/config/report_manager_log.config"
graphdb_connector_log: "ckg/config/graphdb_connector_log.config"
graphdb_builder_log: "ckg/config/graphdb_builder_log.config"
analytics_factory_log: "ckg/config/analytics_factory_log.config"
