version: 1.0
ckg_directory: "C:./local-data"
data_directory: "C:./local-data"
archive_directory: "C:./local-data"
databases_directory: "C:./local-data"
experiments_directory: "C:./local-data"
ontologies_directory: "C:./local-data"
users_directory: "C:./local-data"
stats_directory: "C:./local-data"
downloads_directory: "C:./local-data"
reports_directory: "C:./local-data"
tmp_directory: "C:./local-data"
imports_directory: "C:./local-data"
imports_databases_directory: "C:./local-data"
imports_experiments_directory: "C:./local-data"
imports_ontologies_directory: "C:./local-data"
imports_users_directory: "C:./local-data"
imports_curated_directory: "C:./local-data"
log_directory: "C:./local-data"
report_manager_log: "C:./local-data"
graphdb_connector_log: "C:./local-data"
graphdb_builder_log: "C:./local-data"
